### ISSUE TITLE
Build reported as failure when it is being queued for running

### ISSUE THREAD

**Issue by MarkGaze** [emisgroup/vsts-dashboard#23]
If a build is not in progress or succeeded the dashboard shows it in red, regardless of whether it was in a failure state before or not.

There doesn't seem to be a "failed" status in the API so this needs investigating

**Comment by benmatselby** [comment]
So I have a branch for this, which makes it the same as https://github.com/benmatselby/donny, but would like to talk this over with you @MarkGaze when I see you.

I wonder if we should have these if statements in a function on the BuildData object, because I think we will run into the same issue for the "date" string on the build widget. If there is no date we say it is "Running" but that is not always the case as you pointed out it could be queued.
